# Generated by Django 2.0.8 on 2018-10-03 17:17

from django.db import migrations, models
import django.db.models.deletion
import microscope.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus', models.TextField(max_length=200)),
                ('species', models.TextField(max_length=200)),
                ('kind', models.TextField(choices=[('nematode', 'nematode'), ('cestode', 'cestode'), ('trematode', 'trematode'), ('protozoa', 'protozoa')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to=microscope.models.ParasiteImage.image_name)),
                ('parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='microscope.Parasite')),
            ],
        ),
        migrations.CreateModel(
            name='ParasiteStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.TextField(choices=[('egg', 'egg'), ('larva', 'larva'), ('cyst', 'cyst'), ('adult', 'adult'), ('trophozoite', 'trophozoite')], max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='parasiteimage',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='microscope.ParasiteStage'),
        ),
    ]
