# Generated by Django 2.0.8 on 2018-10-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parasiteimage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parasiteimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parasiteimage',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('disabled', 'disabled')], default='pending', max_length=200),
        ),
        migrations.AddField(
            model_name='parasiteimage',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parasiteimage',
            name='upload_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parasiteimage',
            name='upload_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parasite_images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parasite',
            name='genus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parasite',
            name='kind',
            field=models.CharField(choices=[('nematode', 'nematode'), ('cestode', 'cestode'), ('trematode', 'trematode'), ('protozoa', 'protozoa')], max_length=200),
        ),
        migrations.AlterField(
            model_name='parasite',
            name='species',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='parasitestage',
            name='stage',
            field=models.CharField(choices=[('egg', 'egg'), ('larva', 'larva'), ('cyst', 'cyst'), ('adult', 'adult'), ('trophozoite', 'trophozoite')], max_length=200),
        ),
    ]
